#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XmasHellAndroid.Resource", IsApplication=true)]

namespace XmasHellAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030008
			public const int common_google_signin_btn_text_dark = 2130903048;
			
			// aapt resource value: 0x7f030000
			public const int common_google_signin_btn_text_dark_default = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int common_google_signin_btn_text_dark_disabled = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int common_google_signin_btn_text_dark_focused = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int common_google_signin_btn_text_dark_pressed = 2130903043;
			
			// aapt resource value: 0x7f030009
			public const int common_google_signin_btn_text_light = 2130903049;
			
			// aapt resource value: 0x7f030004
			public const int common_google_signin_btn_text_light_default = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int common_google_signin_btn_text_light_disabled = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int common_google_signin_btn_text_light_focused = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int common_google_signin_btn_text_light_pressed = 2130903047;
			
			// aapt resource value: 0x7f03000a
			public const int common_google_signin_btn_tint = 2130903050;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Splash = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int adjust_height = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int adjust_width = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int auto = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int dark = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int icon_only = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int light = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int none = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int standard = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int wide = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040027
			public const int ApplicationName = 2130968615;
			
			// aapt resource value: 0x7f040013
			public const int achievement_defeat_xmas_ball = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int achievement_defeat_xmas_bell = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int achievement_defeat_xmas_candy = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int achievement_defeat_xmas_gift = 2130968599;
			
			// aapt resource value: 0x7f040019
			public const int achievement_defeat_xmas_log = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int achievement_defeat_xmas_reindeer = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int achievement_defeat_xmas_santa = 2130968604;
			
			// aapt resource value: 0x7f040015
			public const int achievement_defeat_xmas_snowflake = 2130968597;
			
			// aapt resource value: 0x7f04001a
			public const int achievement_defeat_xmas_snowman = 2130968602;
			
			// aapt resource value: 0x7f040018
			public const int achievement_defeat_xmas_tree = 2130968600;
			
			// aapt resource value: 0x7f040011
			public const int app_id = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int common_google_play_services_enable_button = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_google_play_services_enable_text = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_enable_title = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_install_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_text = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_title = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_notification_ticker = 2130968582;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_unknown_issue = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_unsupported_text = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_update_button = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_update_text = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_update_title = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_updating_text = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_wear_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_open_on_phone = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int common_signin_button_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int common_signin_button_text_long = 2130968591;
			
			// aapt resource value: 0x7f04001d
			public const int leaderboard_xmas_ball = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int leaderboard_xmas_bell = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int leaderboard_xmas_candy = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int leaderboard_xmas_gift = 2130968609;
			
			// aapt resource value: 0x7f040023
			public const int leaderboard_xmas_log = 2130968611;
			
			// aapt resource value: 0x7f040025
			public const int leaderboard_xmas_reindeer = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int leaderboard_xmas_santa = 2130968614;
			
			// aapt resource value: 0x7f04001f
			public const int leaderboard_xmas_snowflake = 2130968607;
			
			// aapt resource value: 0x7f040024
			public const int leaderboard_xmas_snowman = 2130968612;
			
			// aapt resource value: 0x7f040022
			public const int leaderboard_xmas_tree = 2130968610;
			
			// aapt resource value: 0x7f040012
			public const int package_name = 2130968594;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
